version: "3"


services:
  test:
    build: .
    image: deep-learning
    command: python mnist_cnn_speed.py
    volumes:
      - ./logs:/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  tensorboard:
    build: .
    volumes:
      - ./logs:/logs
    command: tensorboard --logdir /logs/fit --bind_all
    ports:
      - "6006:6006"
